### ISSUE TITLE
Institution provided by OFX is empty and no fid supplied! Erorr with manual download

### ISSUE THREAD

**Issue by graven04** [egh/ledger-autosync#137]
I keep getting this error when i try to process my ofx files. My bank isn't on ofxhome.com so i had to manually download my transactions. However when i try to process them i get this error: 

Traceback (most recent call last):
  File "/home/user/.local/bin/ledger-autosync", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/user/.local/pipx/venvs/ledger-autosync/lib/python3.11/site-packages/ledgerautosync/cli.py", line 474, in run
    import_ofx(ledger, args)
  File "/home/user/.local/pipx/venvs/ledger-autosync/lib/python3.11/site-packages/ledgerautosync/cli.py", line 195, in import_ofx
    converter = make_ofx_converter(
                ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/ledger-autosync/lib/python3.11/site-packages/ledgerautosync/cli.py", line 132, in make_ofx_converter
    return OfxConverter(
           ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/ledger-autosync/lib/python3.11/site-packages/ledgerautosync/converter.py", line 322, in __init__
    raise EmptyInstitutionException(
ledgerautosync.EmptyInstitutionException: 'Institution provided by OFX is empty and no fid supplied!'

**Comment by egh** [comment]
I think your OFX file is somewhat malformed. But if you pass in the `--fid` option you should be able to fix it. Just choose a number for fid and be consistent about it. It could probably just be `--fid 1`.

**Comment by graven04** [comment]
Great, thank you. This has worked now.
