### ISSUE TITLE
TypeError: argument of type 'int' is not iterable on ofxclient setup

### ISSUE THREAD

**Issue by androclus** [egh/ledger-autosync#31]
Hi, I don't know if this is reproduceable or not, but when setting up ofxclient, I seemed to have an error. That will be shown below. However, it apparently did not stop the setup from creating the correct ~/ofxclient.ini file.  So it must have been some kind of warning. I am willing to try to remove my ofxclient.ini and try to reproduce it if you like.

I am on debian jessie 8.8.0 with all latest patches applied. I got my copy of ledger-autosync via pip as of today.

Here is the output:

```
$ ofxclient
+----------------------------------
Main
Edit /home/jeff/ofxclient.ini to
change descriptions or ofx options
+----------------------------------
(A) Add an account
(Q) Quit
choice> A
+----------------------------------
Add account
+----------------------------------
------
Notice
------
You are about to search for bank connection information
on a third party website.  This means you are trusting
http://ofxhome.com and their security policies.

You will be sending your bank name to this website.
------
bank name eg. "express" (enter to exit)> xxxxxx
(0) XXXXXX
choice> 0
------
Notice
------
You are about to test to make sure your username and password
are correct.  This means you will be sending it to the URL below.
If the URL does not appear to belong to your bank then you should
exit this program by hitting CTRL-C.
  bank name: XXXXXX
  bank url:  https://xxx.xxxxxx.xxx
------
username> xxxxxxxxxx
password> 
password> 
authentication failed: User or Member password invalid
username> xxxxxxxxxx
password> 
+----------------------------------
Main
Edit /home/jeff/ofxclient.ini to
change descriptions or ofx options
+----------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/ofxclient", line 11, in <module>
    load_entry_point('ofxclient==2.0.3', 'console_scripts', 'ofxclient')()
  File "/usr/local/lib/python2.7/dist-packages/ofxclient/cli.py", line 63, in run
    main_menu(args)
  File "/usr/local/lib/python2.7/dist-packages/ofxclient/cli.py", line 71, in main_menu
    accounts = GlobalConfig.accounts()
  File "/usr/local/lib/python2.7/dist-packages/ofxclient/config.py", line 216, in accounts
    for s in self.parser.sections()]
  File "/usr/local/lib/python2.7/dist-packages/ofxclient/config.py", line 301, in _section_to_account
    section_items = dict(self.parser.items(section))
  File "/usr/local/lib/python2.7/dist-packages/ofxclient/config.py", line 100, in items
    for k, v in ConfigParser.items(self, section):
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 663, in _interpolate
    if value and "%(" in value:
TypeError: argument of type 'int' is not iterable
$ _
```

Let me know if you need me to supply any additional information.

**Comment by androclus** [comment]
BTW, I just realized that it may not be appropriate to post this here, as ofxclient probably just got installed via pip as a dependency, yes?

So I posted the same info over at [an issue on the ofxclient project](https://github.com/captin411/ofxclient/issues/21), and feel free to delete here if you like.

**Comment by egh** [comment]
Thanks! But you are correct, that is not my code and the right place to post it is on ofxclient.
