### ISSUE TITLE
Crash when (hledger) journal is empty

### ISSUE THREAD

**Issue by gnoutchd** [egh/ledger-autosync#72]
hledger 1.10, ledger-autosync 7a303f3a. With `$LEDGER_FILE` pointing to a zero-length file, `ledger-autosync some-ofx-from-discovercard.ofx` gets me:

```
Traceback (most recent call last):
  File "/home/gnoutchd/ofx/ofxenv/bin/ledger-autosync", line 11, in <module>
    load_entry_point('ledger-autosync', 'console_scripts', 'ledger-autosync')()
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/cli.py", line 355, in run
    import_ofx(ledger, args)
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/cli.py", line 178, in import_ofx
    print_results(converter, ofx, ledger, txns, args)
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/cli.py", line 74, in print_results
    print(converter.convert(txn).format(args.indent))
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/converter.py", line 423, in convert
    exclude=self.name))])
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/converter.py", line 247, in mk_dynamic_account
    account = self.lgr.get_account_by_payee(payee, exclude)
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/ledgerwrap.py", line 80, in get_account_by_payee
    self.load_payees()
  File "/home/gnoutchd/ofx/ledger-autosync/ledgerautosync/ledgerwrap.py", line 270, in load_payees
    next(r)  # skip headers
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
StopIteration
```

Adding a transaction to `$LEDGER_FILE` fixes it.

This patch also fixes it:

```
diff --git a/ledgerautosync/ledgerwrap.py b/ledgerautosync/ledgerwrap.py
index 5387994..de46d94 100644
--- a/ledgerautosync/ledgerwrap.py
+++ b/ledgerautosync/ledgerwrap.py
@@ -267,7 +267,6 @@ class HLedger(MetaLedger):
             self.payees = {}
             cmd = ["reg", "-O", "csv"]
             r = csv.DictReader(self.run(cmd).splitlines())
-            next(r)  # skip headers
             for line in r:
                 self.add_payee(line['description'], line['account'])
```

(I think `DictReader` already consumes the headers?)

**Comment by egh** [comment]
Makes sense to me, see #73
